apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# TODO: Make sure the openshift-operators and radius namespaces are complete before synching.
resources:
- downloads
- firefox
- home-automation
- media-servers
- metallb-system
- openshift-ingress
- openshift-ingress-operator
- home-routes
# - openshift-operators
- nfs-provisioner
- photos
- pihole
# - radius
- tailscale
- vpn
- vscode
