apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  project: mars-configuration
  source:
    path: mercury/namespaces/nfs-provisioner
    repoURL: git@github.com:MichaelWasher/HomeLab-public.git
    targetRevision: HEAD
