apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  host: grafana.apps.mars.michael-washer.com
  path: /
  port:
    targetPort: 3000
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
  tls:
      termination: edge   
      insecureEdgeTerminationPolicy: Redirect
