apiVersion: v1
kind: Service
metadata:
  name: frigate
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5000
    targetPort: http
  - name: rtsp
    port: 8554
    targetPort: rtsp
  - name: rtmp
    port: 1935
    targetPort: rtmp
  selector:
    app.kubernetes.io/instance: frigate
    app.kubernetes.io/name: frigate
