apiVersion: v1
kind: Service
metadata:
  name: mqtt-ext
  namespace: automation
spec:
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: LoadBalancer
  selector:
    app: mosquitto

---


apiVersion: v1
kind: Service
metadata:
  name: mqtt
  namespace: automation
spec:
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
  type: ClusterIP
  selector:
    app: mosquitto
