apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 192.168.1.100
            - name: NFS_PATH
              value: /NFS-Provisioner/
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.1.100
            path: /NFS-Provisioner/
