# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: appconfig-radarr
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Mi
# ---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: media-movies-radarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: torrents-radarr
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-radarr-config
  namespace: downloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local
  volumeName: local-radarr-config
