apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage
spec:
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local