apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-config
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual