apiVersion: v1
data:
  configuration.yaml: |+
    homeassistant: true
    permit_join: true
    # Docker Compose makes the MQTT-Server available using "mqtt" hostname
    mqtt:
      base_topic: zigbee2mqtt
      server: mqtt://mqtt.home-automation.svc.cluster.local
    # Zigbee Adapter path
    serial:
      port: >-
        /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230525180933-if00
      adapter: ezsp
    # Enable the Zigbee2MQTT frontend
    frontend:
      port: 8080
    # Let Zigbee2MQTT generate a new network key on first start
    advanced:
      network_key: GENERATE

kind: ConfigMap
metadata:
  name: zigbee2mqtt
  namespace: openshift-kube-apiserver
