kind: ConfigMap
apiVersion: v1
metadata:
  name: shadowsocks-server
  namespace: media
data:
  config.json: |
    {
      "servers":
        [
          {
            "fast_open": false,
            "method": "none",
            "mode": "tcp_and_udp",
            "password": "password",
            "server": "::",
            "server_port": 8388,
          }
        ],
      "log": {
        level: 5
      }
    }
    
