---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: jellyfin
  labels:
    app: jellyfin
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.org/websocket-services: jellyfin
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - jellyfin.apps.mercury.michael-washer.com
      secretName: jellyfin-tls
  ingressClassName: openshift-default
  rules:
    - host: jellyfin.apps.mercury.michael-washer.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: jellyfin
                port:
                  name: http

