---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ombi
  labels:
    app: ombi
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.org/websocket-services: ombi
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - ombi.apps.mars.michael-washer.com
      secretName: ombi-tls
  ingressClassName: openshift-default
  rules:
    - host: ombi.apps.mars.michael-washer.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ombi
                port:
                  name: http

