---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-grafana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: appconfig-grafana
    namespace: monitoring
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Grafana
      server: 192.168.2.100