apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: mercury
  name: photoprism-michael
spec:
  host: photoprism.apps.mercury.michael-washer.com
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  port:
    targetPort: 8080
  to:
    kind: Service
    name: photoprism-michael
    weight: 100
  wildcardPolicy: None
