apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-ingress
resources:
- namespaces/openshift-ingress
- namespaces/openshift-ingress-operator
- cluster-scoped-resources