apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - github:
      clientID: Ov23liGlOqMlGnjqnBD2
      clientSecret:
        name: github-client-secret
      hostname: ""
      organizations:
      - support-tools
    mappingMethod: claim
    name: github
    type: GitHub
