apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: frigate-camera-network
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "vlan",
      "master": "enp7s0",
      "vlanId": 4,
      "ipam": {
        "type": "static",
         "addresses": [
            {
              "address": "192.168.3.10/24"
            }
          ]
      }
    }
