apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  labels:
    app: lidarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      name: lidarr-pod
      labels:
        app: lidarr
        app-group: arr
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      automountServiceAccountToken: false
      serviceAccountName: lidarr
      containers:
        - name: lidarr
          imagePullPolicy: Always
          image: ghcr.io/linuxserver/lidarr
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: "Pacific/Auckland"
          ports:
            - containerPort: 8686 #Web
          volumeMounts:
            - mountPath: /config
              name: config-vol
            - mountPath: /music
              name: media-vol
            - mountPath: /downloads
              name: download-vol
      # NOTE: Required due to Gluetun limitations and blocked DNS
      # For more information, see: https://github.com/qdm12/dns/issues/109
      # TODO: Remove when resolved
      hostAliases:
      - hostnames:
        - lidarr.downloads.svc.cluster.local
        ip: 172.30.60.60
      - hostnames:
        - prowlarr.downloads.svc.cluster.local
        ip: 172.30.54.50
      - hostnames:
        - radarr.downloads.svc.cluster.local
        ip: 172.30.161.79
      - hostnames:
        - readarr.downloads.svc.cluster.local
        ip: 172.30.40.47
      - hostnames:
        - sonarr.downloads.svc.cluster.local
        ip: 172.30.38.45
      - hostnames:
        - switzerland.vpn.svc.cluster.local
        ip: 172.30.211.33
      - hostnames:
        - deluge.downloads.svc.cluster.local
        ip: 172.30.57.131 
      # ENDNOTE ----------
      volumes:
        - name: media-vol
          persistentVolumeClaim:
            claimName: media-music-lidarr
        - name: config-vol
          persistentVolumeClaim:
            claimName: appconfig-lidarr
        - name: download-vol
          persistentVolumeClaim:
            claimName: torrents-lidarr
