apiVersion: apps/v1
kind: Deployment
metadata:
  name: readarr
  labels:
    app: readarr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: readarr
  template:
    metadata:
      name: readarr
      labels:
        app: readarr
        app-group: arr
    spec:
      serviceAccountName: readarr
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      automountServiceAccountToken: false
      containers:
        - name: readarr
          imagePullPolicy: Always
          image: ghcr.io/linuxserver/readarr:develop
          resources:
            limits:
              memory: 500Mi
              cpu: 250m
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: TZ
              value: "Pacific/Auckland"
          ports:
            - containerPort: 8787 #Web
          volumeMounts:
            - mountPath: /books
              name: data
            - mountPath: /config
              name: config-vol
            - mountPath: /downloads
              name: download-vol
      # NOTE: Required due to Gluetun limitations and blocked DNS
      # For more information, see: https://github.com/qdm12/dns/issues/109
      # TODO: Remove when resolved
      hostAliases:
      - hostnames:
        - lidarr.downloads.svc.cluster.local
        ip: 172.30.60.60
      - hostnames:
        - prowlarr.downloads.svc.cluster.local
        ip: 172.30.54.50
      - hostnames:
        - radarr.downloads.svc.cluster.local
        ip: 172.30.161.79
      - hostnames:
        - readarr.downloads.svc.cluster.local
        ip: 172.30.40.47
      - hostnames:
        - sonarr.downloads.svc.cluster.local
        ip: 172.30.38.45
      - hostnames:
        - switzerland.vpn.svc.cluster.local
        ip: 172.30.211.33
      - hostnames:
        - deluge.downloads.svc.cluster.local
        ip: 172.30.57.131 
      # ENDNOTE ----------

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: media-books-readarr
        - name: config-vol
          persistentVolumeClaim:
            claimName: appconfig-readarr
        - name: download-vol
          persistentVolumeClaim:
            claimName: torrents-readarr
