apiVersion: apps/v1
kind: Deployment
metadata:
  name: unpackerr
  labels:
    app: unpackerr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: unpackerr
  template:
    metadata:
      name: unpackerr-pod
      labels:
        app: unpackerr
        app-group: arr
    spec:
      serviceAccount: unpackerr
      serviceAccountName: unpackerr
      automountServiceAccountToken: false
      containers:
        - name: unpackerr
          imagePullPolicy: Always
          image: docker.io/golift/unpackerr
          args:
          - "-c /config/unpackerr.conf"
          securityContext:
            privileged: true
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              cpu: "100m"
              memory: 100Mi
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Australia/Brisbane"
          ports:
            - containerPort: 5656 #Web
          volumeMounts:
            - mountPath: /config
              name: config-vol
            - mountPath: /downloads
              name: download-vol
      # NOTE: Required due to Gluetun limitations and blocked DNS
      # For more information, see: https://github.com/qdm12/dns/issues/109
      # TODO: Remove when resolved
      hostAliases:
      - hostnames:
        - lidarr.downloads.svc.cluster.local
        ip: 172.30.60.60
      - hostnames:
        - prowlarr.downloads.svc.cluster.local
        ip: 172.30.54.50
      - hostnames:
        - radarr.downloads.svc.cluster.local
        ip: 172.30.161.79
      - hostnames:
        - readarr.downloads.svc.cluster.local
        ip: 172.30.40.47
      - hostnames:
        - sonarr.downloads.svc.cluster.local
        ip: 172.30.38.45
      - hostnames:
        - switzerland.vpn.svc.cluster.local
        ip: 172.30.211.33
      - hostnames:
        - deluge.downloads.svc.cluster.local
        ip: 172.30.57.131 
      # ENDNOTE ----------
      volumes:
        - name: config-vol
          persistentVolumeClaim:
            claimName: appconfig-unpackerr
        - name: download-vol
          persistentVolumeClaim:
            claimName: torrents-unpackerr
