apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: aruba
spec: 
  port:
    targetPort: 4343
  to:
    kind: Service
    name: aruba
    weight: 100
  wildcardPolicy: None
  tls:
      termination: reencrypt   
      insecureEdgeTerminationPolicy: Redirect
