apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qnap
spec: 
  host: qnap.apps.mars.michael-washer.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: qnap
    weight: 100
  wildcardPolicy: None
  tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
