apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpudeviceplugin
spec:
  image: registry.connect.redhat.com/intel/intel-gpu-plugin@sha256:cfbdee9feb786d22492212be11e63d3c4095dca019a5a23cdff644f209c38fd6
  initImage: registry.connect.redhat.com/intel/intel-gpu-initcontainer@sha256:5abcc534c54b21f52b96500c745b578be78288be1374e70f83af3a9363ddda0b
  preferredAllocationPolicy: none
  sharedDevNum: 4
  logLevel: 4
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
