---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-deluge
  labels:
    type: local
spec:
  claimRef:
    name: appconfig-deluge
    namespace: downloads
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Deluge
      server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-deluge
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: media-deluge
    namespace: downloads
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Movies
      server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrents-deluge
  labels:
    type: local
spec:
  claimRef:
    name: torrents-deluge
    namespace: downloads
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /Torrents
    server: 192.168.1.100