---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-firefox
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: appconfig-firefox
    namespace: firefox
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Firefox
      server: 192.168.1.100