---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-firefox-downloads
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  claimRef:
    name: appconfig-firefox-downloads
    namespace: downloads
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /FirefoxDownloads
      server: 192.168.1.100