---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: frigate-media
    namespace: home-automation
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Frigate
      server: 192.168.2.100
