---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  claimRef:
    name: homeassistant-config
    namespace: home-automation
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /HomeAssistant
      server: 192.168.1.100
