---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-movies
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: movies
    namespace: media-servers
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Movies
      server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-music
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: music
    namespace: media-servers
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Music
      server: 192.168.1.100

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-tv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: tv
    namespace: media-servers
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /TV
      server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-jellyfin
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  claimRef:
    name: appconfig-jellyfin
    namespace: media-servers
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /Jellyfin
    server: 192.168.1.100

