---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ombi-config
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  claimRef:
    name: ombi-config
    namespace: media-servers
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Ombi
      server: 192.168.1.100
