---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-photoprism
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: appconfig-photoprism
    namespace: photos
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Photoprism
      server: 192.168.1.100

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: photoprism-original-photos
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  claimRef:
    name: photoprism-original-photos
    namespace: photos
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Photos
      server: 192.168.1.100