apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  claimRef:
    name: zigbee2mqtt
    namespace: home-automation
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /Zigbee2MQTT
      server: 192.168.1.100
