apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mosquitto
  name: mosquitto-deployment
  namespace: automation
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mosquitto
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: docker.io/library/eclipse-mosquitto:2
        imagePullPolicy: IfNotPresent
        name: mosquitto
        ports:
        - containerPort: 1883
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: mqtt-config-volume
          mountPath: /mosquitto/config/
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
      volumes:
      - name: mqtt-config-volume
        configMap:
          name: mosquitto-config
      - name: telegraf-config-volume
        configMap:
          name: telegraf-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30