apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: home-automation
spec:
  selector:
    matchLabels:
      app: nodered
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodered
    spec:
      serviceAccount: nodered
      serviceAccountName: nodered
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: nodered
        image: nodered/node-red:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: 1880
          name: http
        volumeMounts:
        - mountPath: /data
          name: nodered
      volumes:
        - name: nodered
          persistentVolumeClaim:
            claimName: nodered-config
