apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      serviceAccount: zigbee2mqtt
      serviceAccountName: zigbee2mqtt
      # DNS Config Required to enable Alpine/musl libc images
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      containers:
      - name: zigbee2mqtt
        image: koenkk/zigbee2mqtt
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 0
          privileged: true
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /dev/
          name: devices
        - mountPath: /app/data
          name: zigbee2mqtt
        - mountPath: /run/dbus
          name: dbus
      volumes:
        - name: zigbee2mqtt
          persistentVolumeClaim:
            claimName: zigbee2mqtt
        - name: devices
          hostPath:
            path: /dev
            type: Directory
        - name: dbus
          hostPath:
            path: /run/dbus
            type: Directory




