---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: appconfig-pihole
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  claimRef:
    name: appconfig-pihole
    namespace: pihole
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /PiHole
      server: 192.168.2.100
