apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appconfig-pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: appconfig-pihole
