apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "michael.washer@icloud.com" # Email registered with Let's Encrypt
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            email: "michael.washer@icloud.com" # Cloudflare email address
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token

        # Limit DNS zones which use the API token
        selector:
          dnsZones:
            - "mercury.michael-washer.com"
            - "mars.michael-washer.com"
