apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
  namespace: openshift-ingress
spec:
  secretName: default-ingress-certificate
  dnsNames:
  - "*.apps.mars.michael-washer.com"
  - "*.mars.michael-washer.com"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  usages:
  - digital signature
  - key encipherment

