apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 100-worker-kernel-arguments-mitigations
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
  - mitigations=off

