# Note: This is required for running the Intel GPU Device Plugin

apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 100-alternative-fw-path-for-worker-nodes  
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
      - firmware_class.path=/var/lib/firmware

