apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Bm6Lduv7CW3n/f8G2PNKXEA=,iv:P1KUd6OXc9TzVh7Oc7x7DbsMW1YQEkCl0NFxUqxyRY0=,tag:NvXcvoB3aN5voVIxprDuUQ==,type:comment]
    api-token: ENC[AES256_GCM,data:b2ia4URRFhrU5i97sh6Jx1w09Qirp+UB12tAIlyL2D9RQj9+9djW/Q==,iv:dMk2uOlAyc/fFJFiFUDhX96RI2hb/Fqnl60X87LCO9A=,tag:MfsgikBfuVrvNTbEVJJP8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-08-22T00:04:13Z"
    mac: ENC[AES256_GCM,data:99opnBtEbpPzRigFX1uCXGTUTWY24YBPdNmGXEk+WvVIB0hJo3GJPyMY4dv1EsNES9qxSwElM+LPxmD1H21s3Kz+zf9TGvKzcQEo90mYDXahTrB81RjfFUbRmxmowGWd7rtt6pjHHNN8O/HnpefnmsKchBHqRdaeGoD6s+VHnA4=,iv:JU+MLS/ebpfMUzBiKE84tI1J/wQhl40aTpgJH8ra4c8=,tag:o5Q8I64MYHQE5QrjFcXfyg==,type:str]
    pgp:
        - created_at: "2023-08-22T00:04:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3pmTy8NIpdnAQgAqj6eLyc7P2dzNEGcYPuxtOwVl7jLY/vckzE8iKOw6vjK
            BXoOsebCxCL1LjJ2EMiW+RZvmsV2zkTORBJFJB+ESYh8eFFPQYQwJq7Zsa2rXV43
            fooROMug7WEFiO+A0csQAQ7JZRh4k7YFaRRoQ3NlJ8n2D2ECp0kurgqTi6u9MaWT
            F2Z2FYwbKXP5oWMr+XRMF53L3mOFmqGn3DUvEhE1gEDeE4nQDLUrcHKwmtrq2ZcX
            /8LNACkKNWpXSmb+Tqeyt1PtZciSSn/sC5p3jwPP0jXlcUcuZszGdTDNfjjSKfh2
            1UMPMw3koq4J99DT0tqtgE2M/AtLkjllzkraHyEyW9RbAQkCEBZQjGd+xXdGxiol
            rkCBh/3ax0MfOf5+AKaDOisk8VSsBcXfi794BpRTux4bdnpegFHziNDrM8lWk33R
            WVBx1C6pHE9cnFTpIk6aVSr4ahxtln/3sUydtA==
            =s45j
            -----END PGP MESSAGE-----
          fp: 904F02AD72DEA59C9428B7DEA2F33A731D799EA5
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
