apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
- ns.yaml
- configmaps
# Remove KSOPs Configuration to private repo
# - secrets
- deployments
- ingress
- rbac
- persistentvolumeclaims
- persistentvolumes
- services
- serviceaccounts
- networkattachmentdefinitions