apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: firefox
spec:
  host: firefox.apps.mercury.michael-washer.com
  path: /
  port:
    targetPort: http
  to:
    kind: Service
    name: firefox
    weight: 100
  wildcardPolicy: None
  tls:
      termination: edge   
      insecureEdgeTerminationPolicy: Redirect
