apiVersion: v1
kind: Service
metadata:
  name: deluge-utp
spec:
  type: ClusterIP
  selector:
    app: deluge
  ports:
    - targetPort: 50123
      port: 50123
      protocol: UDP
      name: utp-udp
    - targetPort: 50123
      port: 50123
      protocol: TCP
      name: utp-tcp

---

apiVersion: v1
kind: Service
metadata:
  name: deluge
spec:
  type: ClusterIP
  selector:
    app: deluge
  ports:
    - targetPort: 8112
      port: 8112
      protocol: TCP
      name: http
