apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  type: ClusterIP
  selector:
    app: prowlarr
  ports:
    - targetPort: 9696
      port: 80
      protocol: TCP
      name: http
  clusterIP: 172.30.54.50
