apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
    - targetPort: 7878
      port: 80
      protocol: TCP
      name: http
  clusterIP: 172.30.161.79