apiVersion: v1
kind: Service
metadata:
  name: readarr
spec:
  type: ClusterIP
  selector:
    app: readarr
  ports:
    - targetPort: 8787
      port: 80
      protocol: TCP
      name: http
  clusterIP: 172.30.40.47