apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  type: ClusterIP
  selector:
    app: sonarr
  ports:
    - targetPort: 8989
      port: 80
      protocol: TCP
      name: http
  clusterIP: 172.30.38.45