apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pihole
  annotations:
    haproxy.router.openshift.io/rewrite-target: "/admin/"
spec:
  host: pihole.apps.mars.michael-washer.com
  port:
    targetPort: http
  to:
    kind: Service
    name: pihole-admin
    weight: 100
  wildcardPolicy: None
  tls:
      termination: edge   
      insecureEdgeTerminationPolicy: Redirect
