apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  namespace: media
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi
    spec:
      serviceAccount: ombi
      serviceAccountName: ombi
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      containers:
      - name: ombi
        image: ghcr.io/linuxserver/ombi:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: 256Mi
            cpu: 0
        env:
          - name: TZ
            value: "Australia/Brisbane"
          - name: DOTNET_GCConserveMemory
            value: "9"
        ports:
          - name: http
            containerPort: 3579
        volumeMounts:
            - mountPath: /config
              name: config-vol
      volumes:
        - name: config-vol
          persistentVolumeClaim:
            claimName: ombi-config
