apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    name: nodered
  name: nodered
  namespace: home-automation
spec:
  host: nodered.apps.mars.michael-washer.com
  path: /
  to:
    kind: Service
    name: nodered
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge   
    insecureEdgeTerminationPolicy: Redirect

