
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-data
  labels:
    type: local
spec:
  capacity:
    storage: 100Gi
  claimRef:
    name: influxdb-data-influxdb-0
    namespace: home-automation
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/emptydirs/influxdb
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mars1
  storageClassName: local