---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 4Gi
  claimRef:
    name: mysql-storage
    namespace: home-automation
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/emptydirs/haas-mysql
