---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  claimRef:
    name: mysql-storage
    namespace: home-automation
  accessModes:
    - ReadWriteOnce
  nfs:
      path: /MySQL
      server: 192.168.2.100
