apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- "system:homeassistant:scc:privileged.yaml"
- "system:frigate:scc:anyuid.yaml"
- "system:mysql:scc:privileged.yaml"
- "system:zigbee2mqtt:scc:privileged.yaml"
- "system:nodered:scc:privileged.yaml"
