apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tailscale
  name: subnet-router
  namespace: tailscale
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tailscale
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
          openshift.io/scc: privileged
      labels:
        app: tailscale
    spec:
        containers:
        - env:
          - name: TS_KUBE_SECRET
            value: tailscale-auth
          - name: TS_USERSPACE
            value: "true"
          - name: TS_AUTHKEY
            valueFrom:
              secretKeyRef:
                key: TS_AUTHKEY
                name: tailscale-auth
                optional: false
          - name: TS_ROUTES
            value: 172.30.0.0/16,192.168.1.0/24,192.168.2.0/24
          image: ghcr.io/tailscale/tailscale:latest
          name: tailscale
          securityContext:
            capabilities:
              drop:
              - MKNOD
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
        preemptionPolicy: PreemptLowerPriority
        priority: 0
        serviceAccountName: tailscale
        tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
