---
apiVersion: v1
kind: Service
metadata:
  name: tdarr
spec:
  type: ClusterIP
  selector:
    app: tdarr-server
  ports:
    - port: 8265
      targetPort: 8265

---
apiVersion: v1
kind: Service
metadata:
  name: tdarr-server
spec:
  type: ClusterIP
  selector:
    app: tdarr-server
  ports:
  - name: web
    port: 8265
    protocol: TCP
    targetPort: 8265
  - port: 8266
    protocol: TCP
    targetPort: 8266
    name: server
